runtime: python27
api_version: 1
threadsafe: no

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?^node_modules/.*$


handlers:
- url: /_ah/admin/.*
  script: google.appengine.ext.admin.application
  login: admin



- url: /static
  static_dir: static


- url: /static
  static_dir: static

- url: /src
  static_dir: src

- url: /build
  static_dir: build

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
